---
- name: Copy rule file
  become: true
  ansible.builtin.copy:
    src: 99-marron-devices.rules
    dest: /etc/udev/rules.d/99-marron-devices.rules
    backup: true

- name: Update udev rule
  become: true
  shell: udevadm trigger
