---
- name: Append the group 'docker' to the user's groups
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: [docker]
    append: yes

- name: Restart docker
  become: true
  shell: service docker restart

- name: Stop and remove marron container
  shell: docker stop marron && docker rm marron
  ignore_errors: true

- name: Pull docker image
  shell: docker pull hakuturu583/marron:latest

- name: Start docker container
  shell:
    cmd: >
      docker run -d --name marron --restart always --net=host
      --device=/dev/motor_teensy:/dev/motor_teensy
      --device=/dev/imu:/dev/imu
      hakuturu583/marron:latest
      ros2 launch marron_driver driver.launch.xml
